<form action=<?= $this->url('post', ['action' => 'update',"id"=>$post["_id"]]) ?> method="post">
<div class="form-group">
    <label for="name">Name:</label>
    <input type="name" class="form-control" id="name" name="name" value="<?php echo $post["name"] ?>">
  </div>
  <div class="form-group">
    <label for="email">Email address:</label>
    <input type="email" class="form-control" id="email" name="email" value="<?php echo $post["username"] ?>">
  </div>
  <div class="form-group">
    <label for="pwd">Old Password:</label>
    <input type="password" class="form-control" id="opwd" name="opwd">
  </div>

  <div class="form-group">
    <label for="pwd">New Password:</label>
    <input type="password" class="form-control" id="npwd" name="npwd">
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
</form>
<?php 

if(!empty($error)){
?>
<br>
<br>
<div class="alert alert-danger">
<?php echo $error  ?>
</div>

<?php  } ?>